name: Build & Push Microservices Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------- PRODUCT MICROSERVICE ----------
      - name: Build & Push productMicroservice
        uses: docker/build-push-action@v5
        with:
          context: .
          file: productMicroservice/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/product-microservice:latest

      # ---------- EMAIL NOTIFICATION ----------
      - name: Build & Push EmailNotificationService
        uses: docker/build-push-action@v5
        with:
          context: .
          file: EmailNotificationService/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/email-notification-service:latest

      # ---------- MOCK SERVICE ----------
      - name: Build & Push mockservice
        uses: docker/build-push-action@v5
        with:
          context: .
          file: mockservice/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mockservice:latest
